miechy=(x for x in ["styczeń","luty","marzec","kwiecień","maj","czerwiec","lipec","sierpień","wrzesień","październik","listopad","grudzień"])
print(next(miechy))
print(next(miechy))
print(next(miechy))
print(next(miechy))
print(next(miechy))
print(next(miechy))
print(next(miechy))
print(next(miechy))
print(next(miechy))
print(next(miechy))
print(next(miechy))
print(next(miechy))
